insert into public.guests (name, qty, source) values
  ('Rin Islam', 1, 'order'),
  ('Kathleen Anderson', 1, 'order'),
  ('Melanie Grayce West', 1, 'order'),
  ('Amy Steiner', 4, 'order'),
  ('Stephanie Meza', 1, 'order'),
  ('Leah Shalev', 1, 'order'),
  ('Narayani Gupta', 1, 'order'),
  ('Tuong Vy Keefe', 1, 'order'),
  ('dani finkelpitney', 1, 'order'),
  ('Jean Jones', 2, 'order'),
  ('Suzanne Ostrander', 1, 'order'),
  ('Holly LaDue', 1, 'order'),
  ('Georgia Peck', 1, 'order'),
  ('Samantha Casuga', 2, 'order'),
  ('Andrea Sperling', 1, 'order'),
  ('Alexandra Wiley', 1, 'order'),
  ('Kristina Ng', 1, 'order'),
  ('Caroline Oliver', 1, 'order'),
  ('Rawah Badrawi', 2, 'order'),
  ('Naama Tamir', 2, 'order'),
  ('Paige Steffy', 2, 'order'),
  ('Cathleen Price', 1, 'order'),
  ('Emma Falkenberry', 1, 'manual'),
  ('Alex Stillman', 1, 'manual'),
  ('Judy Linden', 1, 'manual'),
  ('Brenna Goldstein', 1, 'manual'),
  ('Sarah New', 1, 'manual');
